// Dummy data for testing and development
export const getMockData = () => {
  return {
    exams: [
      {
        id: 'pte-academic',
        name: 'PTE',
        display_name: 'PTE Academic',
        description: 'Pearson Test of English Academic',
        duration_minutes: 200,
        total_score: 90,
        is_active: true,
        sections: [
          {
            id: 'pte-speaking',
            name: 'speaking',
            display_name: 'Speaking',
            description: 'Speaking tasks',
            duration_minutes: 77,
            order_index: 1,
            question_types: [
              {
                id: 'pte-read-aloud',
                name: 'read_aloud',
                display_name: 'Read Aloud',
                description: 'Read the text aloud clearly and naturally',
                input_type: 'text',
                response_type: 'audio',
                scoring_method: 'ai_auto',
                time_limit_seconds: 40,
                order_index: 1,
              },
              {
                id: 'pte-repeat-sentence',
                name: 'repeat_sentence',
                display_name: 'Repeat Sentence',
                description:
                  'Listen carefully and repeat exactly what you hear',
                input_type: 'audio',
                response_type: 'audio',
                scoring_method: 'ai_auto',
                time_limit_seconds: 15,
                order_index: 2,
              },
              {
                id: 'pte-describe-image',
                name: 'describe_image',
                display_name: 'Describe Image',
                description:
                  'Look at the image and describe what you see in detail',
                input_type: 'image',
                response_type: 'audio',
                scoring_method: 'ai_auto',
                time_limit_seconds: 40,
                order_index: 3,
              },
            ],
          },
          {
            id: 'pte-writing',
            name: 'writing',
            display_name: 'Writing',
            description: 'Writing tasks',
            duration_minutes: 32,
            order_index: 2,
            question_types: [
              {
                id: 'pte-summarize-written-text',
                name: 'summarize_written_text',
                display_name: 'Summarize Written Text',
                description:
                  'Read the passage and summarize it in one sentence (5-75 words)',
                input_type: 'text',
                response_type: 'text',
                scoring_method: 'ai_auto',
                time_limit_seconds: 600,
                order_index: 1,
              },
              {
                id: 'pte-write-essay',
                name: 'write_essay',
                display_name: 'Write Essay',
                description: 'Write a 200-300 word essay on the given topic',
                input_type: 'text',
                response_type: 'text',
                scoring_method: 'ai_manual_review',
                time_limit_seconds: 1200,
                order_index: 2,
              },
            ],
          },
        ],
      },
      {
        id: 'ielts-academic',
        name: 'IELTS',
        display_name: 'IELTS Academic',
        description: 'International English Language Testing System Academic',
        duration_minutes: 165,
        total_score: 9,
        is_active: true,
        sections: [
          {
            id: 'ielts-writing',
            name: 'writing',
            display_name: 'Writing',
            description: 'Academic writing',
            duration_minutes: 60,
            order_index: 1,
            question_types: [
              {
                id: 'ielts-task1',
                name: 'task1',
                display_name: 'Writing Task 1',
                description:
                  'Describe the visual information in at least 150 words',
                input_type: 'image',
                response_type: 'text',
                scoring_method: 'ai_manual_review',
                time_limit_seconds: 1200,
                order_index: 1,
              },
              {
                id: 'ielts-task2',
                name: 'task2',
                display_name: 'Writing Task 2',
                description: 'Write an essay of at least 250 words',
                input_type: 'text',
                response_type: 'text',
                scoring_method: 'ai_manual_review',
                time_limit_seconds: 2400,
                order_index: 2,
              },
            ],
          },
          {
            id: 'ielts-speaking',
            name: 'speaking',
            display_name: 'Speaking',
            description: 'Speaking interview',
            duration_minutes: 15,
            order_index: 4,
            question_types: [
              {
                id: 'ielts-part1',
                name: 'part1',
                display_name: 'Part 1 - Introduction',
                description:
                  'Answer general questions about yourself and familiar topics',
                input_type: 'text',
                response_type: 'audio',
                scoring_method: 'ai_manual_review',
                time_limit_seconds: null,
                order_index: 1,
              },
              {
                id: 'ielts-part2',
                name: 'part2',
                display_name: 'Part 2 - Cue Card',
                description:
                  'Speak about the topic on the cue card for 1-2 minutes',
                input_type: 'text',
                response_type: 'audio',
                scoring_method: 'ai_manual_review',
                time_limit_seconds: 120,
                order_index: 2,
              },
            ],
          },
        ],
      },
    ],
    questions: [
      {
        id: 'q_pte_read_aloud_001',
        question_type_id: 'pte-read-aloud',
        title: 'Read Aloud - Climate Change',
        content:
          'Climate change represents one of the most significant challenges facing humanity in the 21st century. Rising global temperatures, melting ice caps, and extreme weather events are clear indicators that our planet is undergoing rapid environmental transformation.',
        instructions:
          'Read the text aloud clearly and naturally. You have 40 seconds to read the text.',
        difficulty_level: 2,
        expected_duration_seconds: 40,
        is_active: true,
        tags: ['environment', 'science', 'climate'],
      },
      {
        id: 'q_pte_describe_image_001',
        question_type_id: 'pte-describe-image',
        title: 'Describe Image - Bar Chart',
        content: 'Look at the bar chart showing smartphone usage by age group.',
        instructions:
          'Describe the image in detail. Include the main trends, key data points, and any significant patterns you observe. You have 25 seconds to prepare and 40 seconds to speak.',
        difficulty_level: 3,
        expected_duration_seconds: 40,
        is_active: true,
        tags: ['data', 'technology', 'statistics'],
      },
      {
        id: 'q_pte_essay_001',
        question_type_id: 'pte-write-essay',
        title: 'Essay - Technology in Education',
        content:
          'Some people believe that technology has made learning easier and more accessible, while others argue that it has made students lazy and dependent. Discuss both views and give your own opinion.',
        instructions:
          'Write a 200-300 word essay. Support your arguments with examples and evidence. You have 20 minutes to complete this task.',
        difficulty_level: 4,
        expected_duration_seconds: 1200,
        is_active: true,
        tags: ['education', 'technology', 'opinion'],
      },
      {
        id: 'q_ielts_task1_001',
        question_type_id: 'ielts-task1',
        title: 'IELTS Writing Task 1 - Line Graph',
        content:
          'The line graph shows the percentage of people using public transport in five different cities from 2000 to 2020.',
        instructions:
          'Summarize the information by selecting and reporting the main features, and make comparisons where relevant. Write at least 150 words.',
        difficulty_level: 3,
        expected_duration_seconds: 1200,
        is_active: true,
        tags: ['data', 'transport', 'trends'],
      },
      {
        id: 'q_ielts_task2_001',
        question_type_id: 'ielts-task2',
        title: 'IELTS Writing Task 2 - Work-Life Balance',
        content:
          'In many countries, people are working longer hours and have less time for family and leisure activities. What are the causes of this trend? What solutions can you suggest?',
        instructions:
          'Give reasons for your answer and include any relevant examples from your own knowledge or experience. Write at least 250 words.',
        difficulty_level: 4,
        expected_duration_seconds: 2400,
        is_active: true,
        tags: ['work', 'lifestyle', 'society'],
      },
      {
        id: 'q_ielts_speaking_part1_001',
        question_type_id: 'ielts-part1',
        title: 'IELTS Speaking Part 1 - Hobbies',
        content: 'What hobbies do you enjoy in your free time?',
        instructions:
          'Answer the question naturally and provide some details about your interests.',
        difficulty_level: 2,
        expected_duration_seconds: null,
        is_active: true,
        tags: ['personal', 'interests', 'conversation'],
      },
      {
        id: 'q_ielts_speaking_part2_001',
        question_type_id: 'ielts-part2',
        title: 'IELTS Speaking Part 2 - Memorable Journey',
        content:
          'Describe a memorable journey you have taken.\n\nYou should say:\n- Where you went\n- Who you went with\n- What you did there\n- And explain why this journey was memorable for you',
        instructions:
          'You have 1 minute to prepare and should speak for 1-2 minutes.',
        difficulty_level: 3,
        expected_duration_seconds: 120,
        is_active: true,
        tags: ['travel', 'experience', 'personal'],
      },
    ],
    users: [
      {
        id: 'admin-user-001',
        full_name: 'Admin User',
        email: 'admin@example.com',
        role: 'admin',
        target_exam: null,
        target_score: null,
      },
      {
        id: 'student-user-001',
        full_name: 'John Smith',
        email: 'john@example.com',
        role: 'student',
        target_exam: 'pte-academic',
        target_score: 79,
      },
      {
        id: 'student-user-002',
        full_name: 'Sarah Johnson',
        email: 'sarah@example.com',
        role: 'student',
        target_exam: 'ielts-academic',
        target_score: 7.5,
      },
    ],
    subscriptionPlans: [
      {
        id: 'pte-free',
        name: 'pte_free',
        display_name: 'PTE Free',
        description: 'Limited PTE practice',
        exam_id: 'pte-academic',
        price_monthly: 0,
        price_yearly: 0,
        currency: 'USD',
        mock_tests_limit: 1,
        practice_questions_limit: 20,
        ai_feedback_enabled: false,
        manual_review_enabled: false,
        trial_days: 0,
        is_active: true,
        sort_order: 1,
      },
      {
        id: 'pte-basic',
        name: 'pte_basic',
        display_name: 'PTE Basic',
        description: 'Essential PTE prep',
        exam_id: 'pte-academic',
        price_monthly: 29.99,
        price_yearly: 299.99,
        currency: 'USD',
        mock_tests_limit: 5,
        practice_questions_limit: 200,
        ai_feedback_enabled: true,
        manual_review_enabled: false,
        trial_days: 7,
        is_active: true,
        sort_order: 2,
      },
      {
        id: 'pte-premium',
        name: 'pte_premium',
        display_name: 'PTE Premium',
        description: 'Complete PTE prep',
        exam_id: 'pte-academic',
        price_monthly: 49.99,
        price_yearly: 499.99,
        currency: 'USD',
        mock_tests_limit: null,
        practice_questions_limit: null,
        ai_feedback_enabled: true,
        manual_review_enabled: true,
        trial_days: 7,
        is_active: true,
        sort_order: 3,
      },
      {
        id: 'ielts-free',
        name: 'ielts_free',
        display_name: 'IELTS Free',
        description: 'Limited IELTS practice',
        exam_id: 'ielts-academic',
        price_monthly: 0,
        price_yearly: 0,
        currency: 'USD',
        mock_tests_limit: 1,
        practice_questions_limit: 20,
        ai_feedback_enabled: false,
        manual_review_enabled: false,
        trial_days: 0,
        is_active: true,
        sort_order: 1,
      },
      {
        id: 'ielts-basic',
        name: 'ielts_basic',
        display_name: 'IELTS Basic',
        description: 'Essential IELTS prep',
        exam_id: 'ielts-academic',
        price_monthly: 29.99,
        price_yearly: 299.99,
        currency: 'USD',
        mock_tests_limit: 5,
        practice_questions_limit: 200,
        ai_feedback_enabled: true,
        manual_review_enabled: false,
        trial_days: 7,
        is_active: true,
        sort_order: 2,
      },
      {
        id: 'ielts-premium',
        name: 'ielts_premium',
        display_name: 'IELTS Premium',
        description: 'Complete IELTS prep',
        exam_id: 'ielts-academic',
        price_monthly: 49.99,
        price_yearly: 499.99,
        currency: 'USD',
        mock_tests_limit: null,
        practice_questions_limit: null,
        ai_feedback_enabled: true,
        manual_review_enabled: true,
        trial_days: 7,
        is_active: true,
        sort_order: 3,
      },
    ],
  };
};
